[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "./broadcast" }, {access = "read", path = "./Images/"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@chimera/=lib/chimera/src/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts'
]